apiVersion: v1
kind: Service
metadata:
  name: goserver-service
spec:
  selector:
    app: goserver
  type: ClusterIP
  ports:
  - name: goserver-service
    port: 80 # Porta do service
    targetPort: 8000 # Porta da imagem docker
    protocol: TCP
